// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by JetBrains T4 Processor
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Helix.Compare
{
    using System;
    #line 2 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
using System.Linq;
    #line default
    #line hidden
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.ForTea.TextTemplating", "42.42.42.42")]
    public partial class CompareTemplate : CompareTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            this.Write("\r\n<!DOCTYPE html>\r\n<html>\r\n\r\n<head lang='ru'>\r\n  <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>\r\n  <title>");
            
            #line 9 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.FileName));
            
            #line default
            #line hidden
            this.Write("</title>\r\n  <meta name='viewport' content='width=device-width, initial-scale=1.0'/>\r\n  <link rel='stylesheet' href='bootstrap.css'>\r\n  <link rel='stylesheet' type='text/css' href='stylesheet.css'>\r\n  <script src='jquery-3.5.1.js'></script>\r\n  <script src='bootstrap.js'></script>\r\n  <script>\r\n    $(document).on(\"click\", \".spoiler-trigger\", function () {\r\n      $(this).parents(\"tr\").nextUntil(\":not(.spoiler-block)\").slideToggle(300);\r\n      $(this).find(\"span\").toggle();\r\n    });\r\n\r\n    $(document).on(\"click\", \".spoiler-trigger-all\", function () {\r\n      $(\".spoiler-block\").slideToggle(300);\r\n      $(this).find(\"span\").toggle()\r\n    });\r\n  </script>\r\n</head>\r\n\r\n<body>\r\n<div class='container'>\r\n  <div class='row'>\r\n    <div class='col-md-2 col-md-offset-10'>\r\n      <label class='switch'>\r\n        <input type='checkbox' id='darkSwitch'>\r\n        <span class='slider round'></span>\r\n      </label>\r\n      <label for='darkSwitch'>Ночной режим</label>\r\n    </div>\r\n    <script src='dark-mode-switch.js'></script>\r\n  </div>\r\n  <div class='row'>\r\n    <h1>");
            
            #line 41 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(_model.FileName));
            
            #line default
            #line hidden
            this.Write(" (только различия)</h1>\r\n  </div>\r\n  <div class='row'>\r\n    <div class='spoiler-trigger-all-div'>\r\n      <a href='javascript:void(0);' class='spoiler-trigger-all'>\r\n        <span style='display: none;'>Свернуть всё</span>\r\n        <span>Развернуть всё</span>\r\n      </a>\r\n    </div>\r\n  </div>\r\n  ");
            #line 51 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 if (_model.TypesAdded.Any())
  { 
            
            #line default
            #line hidden
            this.Write("    <div class='row'>\r\n      <h2>Добавленные типы</h2>\r\n      <table title='Добавленные типы' class='table table-hover'>\r\n        <thead>\r\n        <tr><th width='100%'>Имя типа</th></tr>\r\n        </thead>\r\n        <tbody>\r\n        ");
            #line 60 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 foreach (var typeName in _model.TypesAdded)
        { 
            
            #line default
            #line hidden
            this.Write("          <tr><td><span class='folder-name'>");
            
            #line 62 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeName));
            
            #line default
            #line hidden
            this.Write("</span></td></tr>\r\n        ");
            #line 63 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        </tbody>\r\n      </table>\r\n    </div>\r\n  ");
            #line 67 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 }
  if (_model.TypesRemoved.Any())
  { 
            
            #line default
            #line hidden
            this.Write("    <div class='row'>\r\n      <h2>Удалённые типы</h2>\r\n      <table title='Удалённые типы' class='table table-hover'>\r\n        <thead>\r\n        <tr><th width='100%'>Имя типа</th></tr>\r\n        </thead>\r\n        <tbody>\r\n        ");
            #line 77 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 foreach (var typeName in _model.TypesRemoved)
        { 
            
            #line default
            #line hidden
            this.Write("          <tr><td><span class='folder-name'>");
            
            #line 79 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeName));
            
            #line default
            #line hidden
            this.Write("</span></td></tr>\r\n        ");
            #line 80 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        </tbody>\r\n      </table>\r\n    </div>\r\n  ");
            #line 84 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n  <div class='row'>\r\n    <h2>Типы в обоих файлах</h2>\r\n    <table title='Типы в обоих файлах' class='table table-hover'>\r\n      <thead>\r\n      <tr>\r\n        <th width='50%'>Метод в старом фрэймворке</th>\r\n        <th width='50%'>Метод в новом фрэймворке</th>\r\n      </tr>\r\n      </thead>\r\n      <tbody>\r\n      ");
            #line 96 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 foreach (var typeCompareResult in _model.TypesCompareResult)
      { 
            
            #line default
            #line hidden
            this.Write("        <tr><td colspan='2'><span class='folder-name' style='color: #204d74'>");
            
            #line 98 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeCompareResult.TypeName));
            
            #line default
            #line hidden
            this.Write("</span></td></tr> \r\n        ");
            #line 99 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 if (typeCompareResult.MethodsAdded.Any())
        { 
            
            #line default
            #line hidden
            this.Write("          <tr><td colspan='2'>Добавленные методы</td></tr>\r\n          ");
            #line 102 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 foreach (var methodName in typeCompareResult.MethodsAdded)
          { 
            
            #line default
            #line hidden
            this.Write("            <tr><td colspan='2'><span class='folder-name'>");
            
            #line 104 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("</span></td></tr>\r\n          ");
            #line 105 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 }
        }
        if (typeCompareResult.MethodsRemoved.Any())
        { 
            
            #line default
            #line hidden
            this.Write("          <tr><td colspan='2'>Удалённые методы</td></tr>\r\n          ");
            #line 110 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 foreach (var methodName in typeCompareResult.MethodsRemoved)
          { 
            
            #line default
            #line hidden
            this.Write("            <tr><td colspan='2'><span class='folder-name'>");
            
            #line 112 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("</span></td></tr>\r\n          ");
            #line 113 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 }
        }
        if (typeCompareResult.MethodsCompareResult.Any())
        { 
            
            #line default
            #line hidden
            this.Write("          <tr><td colspan='2'>Методы в обоих типах</td></tr>\r\n          ");
            #line 118 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 foreach (var methodsCompareResult in typeCompareResult.MethodsCompareResult)
          { 
            
            #line default
            #line hidden
            this.Write("            <tr><td colspan='2'><span class='folder-name'>");
            
            #line 120 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodsCompareResult.MethodName));
            
            #line default
            #line hidden
            this.Write("</span></td></tr>\r\n            <tr><td colspan='2'><span class='folder-name'>");
            
            #line 121 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodsCompareResult.MethodBodyStatus));
            
            #line default
            #line hidden
            this.Write("</span></td></tr>\r\n            <tr>\r\n              <td>\r\n                ");
            #line 124 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 foreach (var line in methodsCompareResult.OldMethodBody)
                { 
            
            #line default
            #line hidden
            this.Write("                  ");
            
            #line 126 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            this.Write("<br/>\r\n                ");
            #line 127 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("              </td>\r\n              <td>\r\n                ");
            #line 130 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 foreach (var line in methodsCompareResult.NewMethodBody)
                { 
            
            #line default
            #line hidden
            this.Write("                  ");
            
            #line 132 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(line));
            
            #line default
            #line hidden
            this.Write("<br/>\r\n                ");
            #line 133 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("              </td>\r\n            </tr>\r\n          ");
            #line 136 "C:\Users\dvsaf\Projects\Helix-XX\Helix.Compare\CompareTemplate.tt"
 }
        }
      } 
            
            #line default
            #line hidden
            this.Write("      </tbody>\r\n    </table>\r\n  </div>\r\n</div>\r\n</body>\r\n\r\n</html>");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("JetBrains.ForTea.TextTemplating", "42.42.42.42")]
    public class CompareTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
